version: "2.1"
services:
  web:
    build: app
    links: 
      - db
    ports: 
      # - 5000:5000
      - "5000"
    environment: 
      FLASK_ENV: development
      MYSQL_DATABASE_USER: root
      MYSQL_DATABASE_PASSWORD: devops#123
      MYSQL_DATABASE_HOST: db
    volumes: 
      - ./app:/app
      - ./appconf/90-graylog.conf:/etc/rsyslog.d/90-graylog.conf
    depends_on:
      - db
  db:
    build: mysqlconf
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: devops#123
      MYSQL_DATABASE: devopstestedb
    volumes: 
      - mysql-db:/var/lib/mysql
      - ./appconf/90-graylog.conf:/etc/rsyslog.d/90-graylog.conf
      - ./mysqlconf/mysql-dump:/docker-entrypoint-initdb.d
  nginx: 
    build: nginxconf
    container_name: production_nginx
    volumes:
      - ./nginxconf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    links: 
      - web
    ports:
      - "5000:80"
volumes:
  mysql-db: